---
title: "My Map with Leaflet"
author: "Vadim K."
date: '2017-03-18'
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


### Paris Free Wifi Network

Here below you can find an interactive map of Free public Wifi hotspots in Paris, France.  
Hope it will be useful ;)
```{r}
#libraries
suppressWarnings(library(stringr))
suppressWarnings(library(leaflet))
suppressWarnings(library(tidyr))


# importing geo data
url1 <- "https://opendata.paris.fr/explore/dataset/liste_des_sites_des_hotspots_paris_wifi/download/?format=csv&timezone=Asia/Baghdad&use_labels_for_header=true"
wifi_df <- read.csv2(url(url1), stringsAsFactors = FALSE)

#making separate columns with latitude & longitude
wifi_df$lat <- str_split(wifi_df$geo_point_2d, 
                         pattern = ", ", simplify = TRUE)[,1]

wifi_df$lng <- str_split(wifi_df$geo_point_2d, 
                         pattern = ", ", simplify = TRUE)[,2]

#small df with numeric formatted coordinates
df <- data.frame(lat = as.numeric(wifi_df$lat),
                 lng = as.numeric(wifi_df$lng))


#custom icon
wifiIcon <- makeIcon(
    iconUrl = "https://t0tem.github.io/DevDataProd_Assignment1/wifi_Logo.png",
    iconWidth = 24, iconHeight = 24
    #,
    #iconAnchorX = 31*215/230/2, iconAnchorY = 16
)

df %>% 
    leaflet() %>% 
    addTiles() %>% 
    addMarkers(icon = wifiIcon, 
               clusterOptions = markerClusterOptions())

```

*Data obtained from [Paris Opendata portal](https://opendata.paris.fr/page/home/)*
